theme = "catppuccin_frappe"

[editor]
cursorline = true
auto-save = true
continue-comments = false
line-number = "relative"
mouse = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
X = "extend_line_above"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
auto-signature-help = false

[keys.insert]
'C-c' = "signature_help"
